### ISSUE TITLE
Merge Request for libGL not being picked up ?

### ISSUE THREAD

**Issue by Tchan0** [KallistiOS/kos-ports#11]
Hello,

I created a small merge request on sourceforge 5 months ago, but it's not being picked up.
Should I request it in another place ?
https://sourceforge.net/p/cadcdev/libgl/merge-requests/

Thanks,

T.

**Comment by ljsebald** [comment]
My apologies for the... very late reply on this.

Alas, I didn't see any sort of notification for either the MR on sourceforge or this issue request for some reason... Anyhow, it has been merged.
