### ISSUE TITLE
Error building micropython port on FreeBSD

### ISSUE THREAD

**Issue by darcagn** [KallistiOS/kos-ports#40]
This error is given on FreeBSD

```
fatal error: alloca.h: No such file or directory
   36 | #include <alloca.h>
      |          ^~~~~~~~~~
```

This header isn't required though, as `alloca` is provided by `stdlib.h`. Editing `dist/micropython-1.21.0/ports/embed/port/mpconfigport_common.h` and changing `alloca.h` to `stdlib.h` will fix compilation.

**Comment by sizious** [comment]
I guess this could be submitted to the micropython project directly? Or we can maybe add a `sed` thing in the port itself..

**Comment by gyrovorbis** [comment]
Damn, what do you guys think? Gotta get this one taken care of... honestly this is kind of their bad, and surely they want to have their own codebase building for FreeBSD? Somebody wanna try PRing this upstream?

**Comment by sizious** [comment]
Yes I think it’s best to submit a PR to them. It needs to be fixed properly imo.

**Comment by darcagn** [comment]
Submitted a fix upstream based on similar PRs submitted to handle `alloca()` for other micropython ports in their tree.

https://github.com/micropython/micropython/pull/13360

**Comment by darcagn** [comment]
My PR was accepted upstream. micropython now builds fine under FreeBSD. Closing issue as solved.
