### ISSUE TITLE
Version check does not work properly on FreeBSD

### ISSUE THREAD

**Issue by darcagn** [KallistiOS/kos-ports#41]
When running a version check like so from bash shell:
`$ $KOS_MAKE -C ../micropython version-check`

The version check will report back:
```
gmake: Entering directory '/opt/toolchains/dc/kos-ports/micropython'
/bin/sh: /opt/toolchains/dc/kos/../kos-ports/scripts/vercmp.sh: not found
micropython 1.21.0 installed. Update to 1.21.0.
gmake: Leaving directory '/opt/toolchains/dc/kos-ports/micropython'
```
But `vercmp.sh` is where it says it should be.

Installing a package works fine, but as a consequence running `build-all.sh` script will re-compile and re-install everything every time regardless if it's installed already.

**Comment by ljsebald** [comment]
Corrected in d906eee.
