### ISSUE TITLE
Opus lib 

### ISSUE THREAD

**Issue by andressbarajas** [KallistiOS/kos-ports#7]
Seems to be broken.   I haven't compiled it before so I am not sure it due to the recent update of repos.  I just ran utils/build-all.sh and encountered a compiler error:

CC       celt/bands.lo
In file included from /opt/toolchains/dc/sh-elf/sh-elf/include/stdio.h:800,
                 from celt/os_support.h:42,
                 from celt/bands.c:40:
/opt/toolchains/dc/sh-elf/sh-elf/include/ssp/stdio.h:40:5: error: unknown type name ‘__va_list’; did you mean ‘va_list’?
   40 |     __va_list)
      |     ^~~~~~~~~
      |     va_list
/opt/toolchains/dc/sh-elf/sh-elf/include/ssp/stdio.h:46:30: error: unknown type name ‘__va_list’; did you mean ‘va_list’?
   46 |      const char *__restrict, __va_list)
      |                              ^~~~~~~~~
      |                              va_list
make[1]: *** [celt/bands.lo] Error 1
make: *** [build-stamp] Error 2

**Comment by ljsebald** [comment]
This was an issue with some of our internal Newlib-related stuff not agreeing with Newlib's implementation of libssp. It has been fixed in the most recent commit of KOS itself.
